// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProvaPowerTools.Models
{
    public partial class Aliquote
    {
        public Aliquote()
        {
            Fatture = new HashSet<Fatture>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(5)]
        [Unicode(false)]
        public string Codice { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descrizione { get; set; }
        public int Valore { get; set; }

        [InverseProperty("IdAliquotaNavigation")]
        public virtual ICollection<Fatture> Fatture { get; set; }
    }
}