// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ProvaPowerTools.Models;

namespace ProvaPowerTools.Models
{
    public partial class AziendaContext
    {

        [DbFunction("east_or_west", "dbo")]
        //public static string east_or_west(decimal? long)
        //{
        //    throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        //}

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
