// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProvaPowerTools.Models
{
    public partial class Fatture
    {
        [Key]
        public int ID { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataFattura { get; set; }
        [Column(TypeName = "money")]
        public decimal Importo { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descrizione { get; set; }
        public int? IdAliquota { get; set; }
        public bool Applicata { get; set; }

        [ForeignKey("IdAliquota")]
        [InverseProperty("Fatture")]
        public virtual Aliquote IdAliquotaNavigation { get; set; }
    }
}