// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProvaPowerTools.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ProvaPowerTools.Models
{
    public partial interface IAziendaContextProcedures
    {
        Task<List<getTotalePerAnnoResult>> getTotalePerAnnoAsync(int? anno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> getTotalePerAnno2Async(int? anno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
